apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-example
  namespace: argocd
spec:
  destination:
    namespace: nginx-helm-example
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/Senan3188/nginx-helm-example.git"
    targetRevision: master
    helm:
     releaseName: my-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
